#!/bin/bash
# script para criar uma VM em ppc64le, aarch64(arm64) e x86_64(amd64)
# via `uvt-kvm` - uvtool, precisa exportar as 2 variaveis `SERIES` e `VM_NAME`
set -o xtrace
echo " ~Install uvtool"
sudo apt update
sudo apt install -y uvtool
echo "~ export SERIES and a VM_NAME"
echo -e "\n ~~ On POWER8 host check if SMT is OFF 'ppc64_cpu --smt=off' \n"
sudo uvt-simplestreams-libvirt sync --source  http://cloud-images.ubuntu.com/daily arch=$(dpkg --print-architecture) label=daily release=$SERIES
# on POWER: 
#  1) `arch` and `uname -m` will give `ppc64le`; 
#  2) `dpkg --print-archi...` will be `ppc64el`
# on ARM: 1) aarch64 and 2) `arm64`
# on X: 1) `x86_64` and 2) `amd64`
echo "~ uvt-simplestreams-libvirt query :: "
sudo uvt-simplestreams-libvirt query
sudo uvt-kvm create $VM_NAME release=$SERIES --cpu 8 --memory 8192 --disk 32
sudo uvt-kvm wait $VM_NAME
echo "~ VM:"
sudo virsh list --all
echo "~ access uvt-kvm ssh $VM_NAME" or "ssh $(uvt-kvm ip $VM_NAME)"
